### ISSUE TITLE
Alternative indexing of photos in tmp -dir?

### ISSUE THREAD

**Issue by heoa** [bootle/DropZone#4]
The issue is with Source/mooupload.php -file.  For some reason, images get named like `1_hello.jpg`, `2_hallo.png`, -- is there some better way to do this?
1. What about this kind of naming `1.jpg`, `2_png`, --?
   
   ```
           $flag = (bool)$_GET['X-File-Resume'] ? FILE_APPEND : 0;
   
           $fileFormat = end(explode('.',$response['name']));
           $filename = $response['id'].'.'.$fileFormat;
           //$filename = $response['id'].'_'.$response['name'];
   ```
2. Or like this, replacing `_` with nothing?
   
   ```
           $flag = (bool)$_GET['X-File-Resume'] ? FILE_APPEND : 0;
           $filename = $response['id'].$response['name'];
   ```

I am unsure whether the _ works over many platforms, ideas?

I am investigating the code [1] on about the line 140.

[1] http://pastie.org/4558045

**Comment by heoa** [comment]
I am extremely confused where the saving is really done? About line 60, I tried to hack the upload_name:

```
        //$response['upload_name'] = $file['name'];

        $fileFormat = end(explode('.',$response['name']));
        $response['upload_name'] = $response['id'].'.'.$fileFormat;
```

but nothing happens, sorry I am newbie but I would like to understand which file specifies the name of the file to be saved, learning slowly.

Does there exist some documentation about how this DropZone -thing is supposed to work? Too many upload -words.

**Comment by juanparati** [comment]
Hi!

The reason because the files are renamed with the identificator prefix in the beginning is because HTML5 allows upload simultaneous files at the same time. So an user can upload for example c:\pictures1\example.jpg and c:\pictures2\example.jpg and the files are not overwritten. However HTML4 don't have this problem because the files are no uploaded asynchronous, so this means that first c:\picture1\example.jpg is uploaded and processed first and c:\pictures2\example.jpg is uploaded and processed after.

The hyphen  symbol (_) works in all platforms.

I don't recommend remove the identificator prefix because 2 files with the same name that are uploading using HTML5 will be mixed and overwritten.

However if you want know the final name and the original name from the client side you can read the property "name" for retrieve  the original file name and the property "upload_name" for retrieve the filename in the server.

I can see that you are using an old version of mooupload.php and I recommend you download the new version because contains a extra functionality that allow you choose a new file prefix.

I can see that you made a very good job with DropZone. Congratulations. I thinking to close MooUpload and start to use DropZone ;)

**Comment by bootle** [comment]
Great, I'll update to the newer MooUpload backend soon, I haven't touched the PHP parts actually since we wrote it from scratch for our apps, so big thanks on the heads up!

Thanks for the nice words Juan! It would be really great to join forces on this one, if you'd like to merge the two projects or help us out with DropZone :)

**Comment by bootle** [comment]
@juanparati @heoa I updated the class with lots of various fixes and changes and updated the PHP file. Sorry for such a long wait guys! The class now should be 100% working. Closing this issue. Thanks!
