### ISSUE TITLE
Possible Reuse jQuery-File-Upload with Bootle DropZone?

### ISSUE THREAD

**Issue by heoa** [bootle/DropZone#5]
This DropZone -feature is in jQuery-File-Upload -widget [1]. I did not get it working as simple as I wanted like your example, but it has a massive amount of follwers and it is actively developed. It is not obvious that it supports the dropzone -feature but you need to Drag&Drop there.
1. I suggest to check whether some modules or features could be reused in your idea? 
2. Are you sure you are not reinventing the wheel?

Since I like the simplicity of your tool, I am not discouraging you to go forward -- just wanting you to be aware of the other similar tool, perhaps coming useful at some moment.

**References**
[1] http://blueimp.github.com/jQuery-File-Upload/

**Comment by bootle** [comment]
Hi heoa, jQuery-File-Upload is a full on product built for jQuery, AFAIK it's way bigger than DropZone, but I'm sure it does the job very well

We built DropZone for our own apps, since we prefer to use the MooTools framework over jQuery. There are many upload libs around, but none is perfect, so we decided to make our own solution. We're not intending to ever compete with others with DropZone, as it's not a product on its own, just a side-effect of our projects which turned out quite well so we decided to share with others and in exchange maybe get some feedback from others. I don't think we reinvented the tool, rather looked into many other libraries (all credited) and borrowed some ideas :)

**Comment by heoa** [comment]
Requested whether something Bootle DropZone could be accomplished easily with jQuery-File-Upload here [1].

I find your tool much clearer, its strenght, but the source code is awful -- I still have not found where you specify the saving -options for the images such as name, dir etc -- why not timestamp?

[1] https://github.com/blueimp/jQuery-File-Upload/issues/1603

**Comment by heoa** [comment]
I would like refactor Bootle more simple so:
1. I moved the new idea about timestamp here [1], why use just numbers? 
2. Why not timestamp or something like that?
3. Perhaps some easy configuration should be done here, I am still puzzled how the DropZone really works -- so many different files. Can you put some short description of each file? 

[1] https://github.com/bootle/DropZone/issues/6

**Comment by bootle** [comment]
I think you missed one thing here: DropZone is a front-end uploading library, what happens to files after their uploaded is handled by a very simple piece of PHP code, which is here just to make the demo work and shouldn't really be used as is. Honestly, I just reused the one developed for MooUpload and haven't even renamed the files, so I take no credit (or responsibility :)) for the PHP. JavaScript is what matters here, PHP should be developed separately to your needs.

As for filenames, backend decides where the files go and what names they get, then JavaScript receives the names upon completion.

if you'd like to contribute with better backend code, feel welcome.
